
package com.factug.factugo.ui.panels;

import com.factug.factugo.entidades.Producto;
import com.factug.factugo.entidades.Result;
import com.factug.factugo.pruebas.PruebaApiRest.Root;
import com.factug.factugo.servicios.ProductoService;
import com.factug.factugo.servicios.impl.ProductoServiceImpl;
import com.factug.factugo.util.ConsultaApi;
import com.factug.factugo.util.Util;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jhordie
 */
public class NuevaVenta extends javax.swing.JPanel {

    /** Creates new form NuevaVenta */
    public NuevaVenta() {
        initComponents();
        txtVendedor.setText(Util.sesionUser.toUpperCase());
        ProductoService service = new ProductoServiceImpl();
        for(Producto p: service.listar()){
            cmbProductos.addItem( ""+ p.getDescripcion() +" S/."+p.getPrecio()+" " );
            /*fila[0]= p.getId(); 
            fila[1]= p.getDescripcion(); 
            fila[2]= p.getPrecio(); 
            fila[3]= p.getStock();
            modelo.addRow(fila);*/
        }
        //tblProductos.setModel(modelo);
        
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnBuscarDNI = new javax.swing.JButton();
        txtDNI = new javax.swing.JTextField();
        txtNombres = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtVendedor = new javax.swing.JTextField();
        cmbProductos = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnAgregarTabla = new javax.swing.JButton();
        spnCantidad = new javax.swing.JSpinner();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtPago = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtNetoPagar = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtDevolver = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        lblSubtotal = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lbligv = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblDescu = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setMaximumSize(new java.awt.Dimension(1200, 830));
        setMinimumSize(new java.awt.Dimension(1200, 830));
        setPreferredSize(new java.awt.Dimension(1200, 830));
        setRequestFocusEnabled(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Open Sans", 1, 14))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jLabel2.setText("DNI:");

        btnBuscarDNI.setText("BUSCAR");
        btnBuscarDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarDNIActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jLabel18.setText("APELLIDOS:");

        jLabel19.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jLabel19.setText("NOMBRES:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBuscarDNI)
                .addGap(48, 48, 48)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuscarDNI, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel19)
                        .addComponent(jLabel18)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        tblProductos.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "N°", "DESCRIPCION", "CANTIDAD", "PRECIO U.", "PRECIO TOTAL", "ACCIONES"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblProductos);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Descripcion", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Open Sans", 1, 14))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jLabel4.setText("Vendedor:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));
        jPanel2.add(txtVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 390, 30));

        cmbProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbProductosActionPerformed(evt);
            }
        });
        jPanel2.add(cmbProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 390, 30));

        jLabel5.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jLabel5.setText("Cantidad:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(601, 77, -1, -1));

        jLabel6.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jLabel6.setText("Producto:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        btnAgregarTabla.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        btnAgregarTabla.setText("Agregar");
        btnAgregarTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarTablaActionPerformed(evt);
            }
        });
        jPanel2.add(btnAgregarTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 60, 143, 50));
        jPanel2.add(spnCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 80, 128, 30));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pagar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Open Sans", 1, 14))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Open Sans", 1, 16)); // NOI18N
        jLabel7.setText("Pago con:");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));
        jPanel3.add(txtPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 200, 35));

        jLabel8.setFont(new java.awt.Font("Open Sans", 1, 16)); // NOI18N
        jLabel8.setText("Neto a Pagar:");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, -1, -1));
        jPanel3.add(txtNetoPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 30, 182, 35));

        jLabel9.setFont(new java.awt.Font("Open Sans", 1, 16)); // NOI18N
        jLabel9.setText("Devolver:");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        txtDevolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDevolverMouseClicked(evt);
            }
        });
        txtDevolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDevolverActionPerformed(evt);
            }
        });
        jPanel3.add(txtDevolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 200, 36));

        jLabel10.setFont(new java.awt.Font("Open Sans", 0, 18)); // NOI18N
        jLabel10.setText("SUBTOTAL:");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 30, -1, 20));

        lblSubtotal.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblSubtotal.setText("S/.00.00");
        jPanel3.add(lblSubtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 30, -1, -1));

        jLabel12.setFont(new java.awt.Font("Open Sans", 0, 18)); // NOI18N
        jLabel12.setText("IGV 18%:");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 60, -1, -1));

        lbligv.setFont(new java.awt.Font("Open Sans", 0, 18)); // NOI18N
        lbligv.setText("S/.00.00");
        jPanel3.add(lbligv, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 60, -1, -1));

        jLabel14.setFont(new java.awt.Font("Open Sans", 0, 18)); // NOI18N
        jLabel14.setText("DSCT:");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 100, -1, -1));

        lblDescu.setFont(new java.awt.Font("Open Sans", 0, 18)); // NOI18N
        lblDescu.setText("S/.00.00");
        jPanel3.add(lblDescu, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 100, -1, -1));

        jLabel16.setFont(new java.awt.Font("Open Sans", 0, 18)); // NOI18N
        jLabel16.setText("TOTAL:");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 160, -1, -1));

        lblTotal.setFont(new java.awt.Font("Open Sans", 0, 18)); // NOI18N
        lblTotal.setText("S/.00.00");
        jPanel3.add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 160, -1, -1));

        jButton3.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon("D:\\CURSO BECA\\FUND DE PROGRAMACIÓN CON JAVA\\SESIONES\\SISTEMA-VENTAS\\FactuGo\\src\\main\\java\\com\\factug\\factugo\\ui\\imgs\\icon_cancelar.png")); // NOI18N
        jButton3.setText("CANCELAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 160, 170, 50));

        jButton4.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon("D:\\CURSO BECA\\FUND DE PROGRAMACIÓN CON JAVA\\SESIONES\\SISTEMA-VENTAS\\FactuGo\\src\\main\\java\\com\\factug\\factugo\\ui\\imgs\\icon_cobrar.png")); // NOI18N
        jButton4.setText("COBRAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 170, 50));

        jButton5.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon("D:\\CURSO BECA\\FUND DE PROGRAMACIÓN CON JAVA\\SESIONES\\SISTEMA-VENTAS\\FactuGo\\src\\main\\java\\com\\factug\\factugo\\ui\\imgs\\icon_guardar.png")); // NOI18N
        jButton5.setText("GUARDAR");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 170, 50));

        jButton6.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon("D:\\CURSO BECA\\FUND DE PROGRAMACIÓN CON JAVA\\SESIONES\\SISTEMA-VENTAS\\FactuGo\\src\\main\\java\\com\\factug\\factugo\\ui\\imgs\\icon_printer.png")); // NOI18N
        jButton6.setText("IMPRIMIR");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 170, 50));
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 140, 210, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1154, Short.MAX_VALUE)
                        .addComponent(jScrollPane1)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtDevolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDevolverActionPerformed
        // TODO add your handling code here:
       //
        
    }//GEN-LAST:event_txtDevolverActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed
    
    int n = 0;
    double subtotal = 0;
    double igv = 0.18;
    double igvSubtotal =0;
    double total = 0;
    private void btnAgregarTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarTablaActionPerformed
        // TODO add your handling code here:
        ProductoService service = new ProductoServiceImpl();
        Producto producto = service.buscar(""+(cmbProductos.getSelectedIndex()+1));
        //Producto producto = new Producto(0, txtDescriAP.getText(), Double.parseDouble(txtPrecioAP.getText()), Integer.parseInt(txtStockAP.getText()) );
        DefaultTableModel modelo=(DefaultTableModel) tblProductos.getModel(); 
        Object [] fila=new Object[6]; 
        fila[0]= n ; 
        fila[1]= producto.getDescripcion();
        fila[2]= spnCantidad.getValue(); 
        fila[3]= producto.getPrecio();
        double precioxcanti = producto.getPrecio() *  Integer.parseInt(spnCantidad.getValue().toString());
        fila[4]= precioxcanti;
        fila[5]= "Eliminar";
        modelo.addRow(fila);
        tblProductos.setModel(modelo);
        n++;
        
        subtotal += precioxcanti;
        lblSubtotal.setText("S/."+subtotal);
        igvSubtotal = subtotal*igv;
        lbligv.setText("S/."+igvSubtotal);
        total = subtotal + igvSubtotal;
        lblTotal.setText("S/."+total);
        txtNetoPagar.setText(""+total);
    }//GEN-LAST:event_btnAgregarTablaActionPerformed

    private void btnBuscarDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarDNIActionPerformed
        // TODO add your handling code here:
        String dni = txtDNI.getText();
        ConsultaApi api = new ConsultaApi();
        try {
            api.ConsultaApidni(dni);
            System.out.println(api.ConsultaApidni(dni));
            Result r = new Result();
            txtNombres.setText(Util.NOMBRECLIENTE);
            txtApellidos.setText(Util.APELLIDOSCLIENTE);
            
        } catch (IOException ex) {
            Logger.getLogger(NuevaVenta.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
        
    }//GEN-LAST:event_btnBuscarDNIActionPerformed

    private void cmbProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProductosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbProductosActionPerformed

    private void txtDevolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDevolverMouseClicked
        // TODO add your handling code here:
         txtDevolver.setText( " "+ (Double.parseDouble(txtPago.getText()) - Double.parseDouble(txtNetoPagar.getText())));
    }//GEN-LAST:event_txtDevolverMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarTabla;
    private javax.swing.JButton btnBuscarDNI;
    private javax.swing.JComboBox<String> cmbProductos;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblDescu;
    private javax.swing.JLabel lblSubtotal;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lbligv;
    private javax.swing.JSpinner spnCantidad;
    private javax.swing.JTable tblProductos;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtDevolver;
    private javax.swing.JTextField txtNetoPagar;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtPago;
    private javax.swing.JTextField txtVendedor;
    // End of variables declaration//GEN-END:variables

}
