
package com.factug.factugo.ui.panels;

import com.factug.factugo.entidades.Producto;
import com.factug.factugo.servicios.ProductoService;
import com.factug.factugo.servicios.impl.ProductoServiceImpl;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jhordie
 */
public class VerProductos extends javax.swing.JPanel {

    /** Creates new form VerProductos */
    public VerProductos() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnEliminarProducto = new javax.swing.JButton();
        btnAgregarProducto = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtDescriAP = new javax.swing.JTextField();
        txtPrecioAP = new javax.swing.JTextField();
        txtStockAP = new javax.swing.JTextField();
        txtIdEP = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnActualizarProducto = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtIdACP = new javax.swing.JTextField();
        txtDescriACP = new javax.swing.JTextField();
        txtPrecioACP = new javax.swing.JTextField();
        txtStockACP = new javax.swing.JTextField();
        btnListarTabla = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setMaximumSize(new java.awt.Dimension(1200, 830));
        setMinimumSize(new java.awt.Dimension(1200, 830));
        setPreferredSize(new java.awt.Dimension(1200, 830));

        tblProductos.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "ID", "DESCRIPCION", "PRECIO", "STOCK"
            }
        ));
        jScrollPane1.setViewportView(tblProductos);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Productos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Open Sans", 1, 14))); // NOI18N
        jPanel1.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Open Sans", 3, 14)); // NOI18N
        jLabel1.setText("Agregar Producto:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        btnEliminarProducto.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        btnEliminarProducto.setIcon(new javax.swing.ImageIcon("D:\\CURSO BECA\\FUND DE PROGRAMACIÓN CON JAVA\\SESIONES\\SISTEMA-VENTAS\\FactuGo\\src\\main\\java\\com\\factug\\factugo\\ui\\imgs\\icon_eliminar.png")); // NOI18N
        btnEliminarProducto.setText("Eliminar Producto");
        btnEliminarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarProductoActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, 210, 35));

        btnAgregarProducto.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        btnAgregarProducto.setIcon(new javax.swing.ImageIcon("D:\\CURSO BECA\\FUND DE PROGRAMACIÓN CON JAVA\\SESIONES\\SISTEMA-VENTAS\\FactuGo\\src\\main\\java\\com\\factug\\factugo\\ui\\imgs\\icon_agregar.png")); // NOI18N
        btnAgregarProducto.setText("Agregar Producto");
        btnAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarProductoActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 290, 35));

        jLabel2.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Descripcion:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 90, -1));

        jLabel3.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Precio:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 90, -1));

        jLabel4.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jLabel4.setText("Stock:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1));

        jLabel5.setFont(new java.awt.Font("Open Sans", 3, 14)); // NOI18N
        jLabel5.setText("Eliminar Producto:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, -1, -1));

        jLabel6.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jLabel6.setText("ID:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, -1, -1));
        jPanel1.add(txtDescriAP, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 210, -1));
        jPanel1.add(txtPrecioAP, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 210, -1));
        jPanel1.add(txtStockAP, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 210, -1));
        jPanel1.add(txtIdEP, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, 140, -1));

        jLabel7.setFont(new java.awt.Font("Open Sans", 3, 14)); // NOI18N
        jLabel7.setText("Actualizar Producto:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 30, -1, -1));

        jLabel8.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Descripcion:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 90, 90, -1));

        jLabel9.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Precio:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 120, 60, -1));

        jLabel10.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Stock:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 150, 50, -1));

        btnActualizarProducto.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        btnActualizarProducto.setIcon(new javax.swing.ImageIcon("D:\\CURSO BECA\\FUND DE PROGRAMACIÓN CON JAVA\\SESIONES\\SISTEMA-VENTAS\\FactuGo\\src\\main\\java\\com\\factug\\factugo\\ui\\imgs\\icon_actualizar.png")); // NOI18N
        btnActualizarProducto.setText("Actualizar Producto");
        btnActualizarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarProductoActionPerformed(evt);
            }
        });
        jPanel1.add(btnActualizarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 190, 280, 35));

        jLabel11.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("ID:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 60, 30, -1));
        jPanel1.add(txtIdACP, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 60, 210, -1));
        jPanel1.add(txtDescriACP, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 90, 210, -1));
        jPanel1.add(txtPrecioACP, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 120, 210, -1));
        jPanel1.add(txtStockACP, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 150, 210, -1));

        btnListarTabla.setText("Actualizar Tabla");
        btnListarTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarTablaActionPerformed(evt);
            }
        });
        jPanel1.add(btnListarTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 260, 130, -1));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 50, 20, 170));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, 20, 170));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProductoActionPerformed
        // TODO add your handling code here:
        ProductoService servicio = new ProductoServiceImpl();
        Producto producto = new Producto(0, txtDescriAP.getText(), Double.parseDouble(txtPrecioAP.getText()), Integer.parseInt(txtStockAP.getText()) );
        servicio.grabar(producto);
        JOptionPane.showMessageDialog(this, "Datos guardado correctamente");
    }//GEN-LAST:event_btnAgregarProductoActionPerformed

    private void btnEliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarProductoActionPerformed
        // TODO add your handling code here:
        ProductoService service = new ProductoServiceImpl();
        service.eliminar(txtIdEP.getText());
        JOptionPane.showMessageDialog(this, "Producto borrado Correctamente");
    }//GEN-LAST:event_btnEliminarProductoActionPerformed

    private void btnListarTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarTablaActionPerformed
        // TODO add your handling code here:
        ProductoService service = new ProductoServiceImpl();
        DefaultTableModel modelo=(DefaultTableModel) tblProductos.getModel(); 

        Object [] fila=new Object[4];
        System.out.println(fila);
        modelo.setRowCount(0);
        for(Producto p: service.listar()){
            fila[0]= p.getId(); 
            fila[1]= p.getDescripcion(); 
            fila[2]= p.getPrecio(); 
            fila[3]= p.getStock();
            modelo.addRow(fila);
        }
        tblProductos.setModel(modelo);

    }//GEN-LAST:event_btnListarTablaActionPerformed

    private void btnActualizarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarProductoActionPerformed
        // TODO add your handling code here:
        ProductoService service = new ProductoServiceImpl();
        Producto producto = new Producto(Integer.parseInt(txtIdACP.getText()), txtDescriACP.getText(), Double.parseDouble(txtPrecioACP.getText()), Integer.parseInt(txtStockACP.getText()) );
        service.actualizar(producto);
        JOptionPane.showMessageDialog(this, "Producto actualizado Correctamente");
    }//GEN-LAST:event_btnActualizarProductoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarProducto;
    private javax.swing.JButton btnAgregarProducto;
    private javax.swing.JButton btnEliminarProducto;
    private javax.swing.JButton btnListarTabla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable tblProductos;
    private javax.swing.JTextField txtDescriACP;
    private javax.swing.JTextField txtDescriAP;
    private javax.swing.JTextField txtIdACP;
    private javax.swing.JTextField txtIdEP;
    private javax.swing.JTextField txtPrecioACP;
    private javax.swing.JTextField txtPrecioAP;
    private javax.swing.JTextField txtStockACP;
    private javax.swing.JTextField txtStockAP;
    // End of variables declaration//GEN-END:variables

}
