/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.ejercicio1.ui.panels;

/**
 *
 * @author Jhordie
 */
public class PnlPrueba02 extends javax.swing.JPanel {

    /**
     * Creates new form PnlPrueba02
     */
    public PnlPrueba02() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        sldNota3 = new javax.swing.JSlider();
        sldNota1 = new javax.swing.JSlider();
        sldNota2 = new javax.swing.JSlider();
        lblNota1 = new javax.swing.JLabel();
        lblNota2 = new javax.swing.JLabel();
        lblNota3 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSalida = new javax.swing.JTextArea();

        jLabel1.setText("NOMBRE:");

        jLabel2.setText("NOTA 1:");

        jLabel3.setText("NOTA 2:");

        jLabel4.setText("NOTA 3:");

        sldNota3.setMajorTickSpacing(10);
        sldNota3.setMaximum(20);
        sldNota3.setMinorTickSpacing(1);
        sldNota3.setPaintLabels(true);
        sldNota3.setPaintTicks(true);
        sldNota3.setToolTipText("");
        sldNota3.setValue(0);
        sldNota3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldNota3StateChanged(evt);
            }
        });

        sldNota1.setMajorTickSpacing(10);
        sldNota1.setMaximum(20);
        sldNota1.setMinorTickSpacing(1);
        sldNota1.setPaintLabels(true);
        sldNota1.setPaintTicks(true);
        sldNota1.setValue(0);
        sldNota1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldNota1StateChanged(evt);
            }
        });

        sldNota2.setMajorTickSpacing(10);
        sldNota2.setMaximum(20);
        sldNota2.setMinorTickSpacing(1);
        sldNota2.setPaintLabels(true);
        sldNota2.setPaintTicks(true);
        sldNota2.setValue(0);
        sldNota2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldNota2StateChanged(evt);
            }
        });

        lblNota1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNota1.setText("0");

        lblNota2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNota2.setText("0");

        lblNota3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNota3.setText("0");

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        txtSalida.setColumns(20);
        txtSalida.setRows(5);
        jScrollPane1.setViewportView(txtSalida);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(27, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sldNota3, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                            .addComponent(sldNota1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sldNota2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNota3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblNota2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblNota1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(41, 41, 41))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(sldNota1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNota1))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(sldNota2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblNota2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(16, 16, 16)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel4)
                        .addGap(60, 60, 60))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sldNota3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNota3))
                        .addGap(44, 44, 44)))
                .addComponent(btnAgregar)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void sldNota1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldNota1StateChanged
        // TODO add your handling code here:
        lblNota1.setText(String.valueOf(sldNota1.getValue()));
    }//GEN-LAST:event_sldNota1StateChanged

    private void sldNota2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldNota2StateChanged
        // TODO add your handling code here:
        lblNota2.setText(String.valueOf(sldNota2.getValue()));

    }//GEN-LAST:event_sldNota2StateChanged

    private void sldNota3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldNota3StateChanged
        // TODO add your handling code here:
        lblNota3.setText(String.valueOf(sldNota3.getValue()));

    }//GEN-LAST:event_sldNota3StateChanged

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        String sNombre = txtNombre.getText();
        double promedio = (sldNota1.getValue() + sldNota2.getValue() + sldNota3.getValue()) / 3.0;
        
        txtSalida.setText("");
        txtSalida.append("Nombre: "+ sNombre + "\n");
        txtSalida.append("Promedio: "+promedio+ "\n");
        String status = "";
        if(promedio >= 0 && promedio <= 10) status = "especial";
        if(promedio >= 10 && promedio <= 13) status = "bajo";
        if(promedio >= 13 && promedio <= 16) status = "regular";
        if(promedio >= 16 && promedio <= 20) status = "sobresaliente";
        
        txtSalida.append("Estatus: "+ status + "\n");
    }//GEN-LAST:event_btnAgregarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNota1;
    private javax.swing.JLabel lblNota2;
    private javax.swing.JLabel lblNota3;
    private javax.swing.JSlider sldNota1;
    private javax.swing.JSlider sldNota2;
    private javax.swing.JSlider sldNota3;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextArea txtSalida;
    // End of variables declaration//GEN-END:variables
}
