
package com.factug.factugo.ui;

import com.factug.factugo.entidades.Usuario;
import com.factug.factugo.servicios.UsuarioService;
import com.factug.factugo.servicios.impl.UsuarioServiceImpl;
import com.factug.factugo.util.Util;
import com.factug.factugo.util.ConexionSQL;
import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Color;
import java.awt.Shape;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.geom.RoundRectangle2D;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.Timer;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Jhordie
 */
public class FrmLogin extends javax.swing.JFrame {

    /** Creates new form FrmLogin */
    public FrmLogin() {
        UIManager.put( "Component.arc", 999 );
        UIManager.put( "Button.arc", 12 );
        UIManager.put( "TextComponent.arc", 999 );
        initComponents();
        this.setLocationRelativeTo(null);
        //System.out.println(lblBgImg.getLocation()); // x10 y10
        this.btnOcultar.setVisible(false);
        //this.txtPass.setEchoChar('*');
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBgImg = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblOlvidaste = new javax.swing.JLabel();
        txtContraRepRegister = new javax.swing.JPasswordField();
        txtContraRegister = new javax.swing.JPasswordField();
        txtCorreoRegister = new javax.swing.JTextField();
        txtUserRegister = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lblRegistrar = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnOcultar = new javax.swing.JLabel();
        btnVer = new javax.swing.JLabel();
        lblITitulo1 = new javax.swing.JLabel();
        lblITitulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        btnIngresar = new javax.swing.JButton();
        lblIngresar = new javax.swing.JLabel();
        lblBg2 = new javax.swing.JLabel();
        lblBg1 = new javax.swing.JLabel();
        switchButton1 = new com.factug.factugo.ui.SwitchButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(870, 600));
        setMinimumSize(new java.awt.Dimension(870, 600));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(870, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(870, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBgImg.setIcon(new javax.swing.ImageIcon("D:\\CURSO BECA\\FUND DE PROGRAMACIÓN CON JAVA\\SESIONES\\SISTEMA-VENTAS\\FactuGo\\src\\main\\java\\com\\factug\\factugo\\ui\\imgs\\img_login.png")); // NOI18N
        getContentPane().add(lblBgImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 400, 580));

        jButton1.setBackground(new java.awt.Color(255, 51, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("X");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 20, -1, -1));

        jLabel5.setFont(new java.awt.Font("Rift Soft", 1, 24)); // NOI18N
        jLabel5.setText("USUARIO:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, -1));

        jLabel6.setFont(new java.awt.Font("Rift Soft", 1, 24)); // NOI18N
        jLabel6.setText("CORREO:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));

        jLabel7.setFont(new java.awt.Font("Rift Soft", 1, 24)); // NOI18N
        jLabel7.setText("CONTRASEÑA:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, -1, -1));

        jLabel8.setFont(new java.awt.Font("Rift Soft", 1, 24)); // NOI18N
        jLabel8.setText("REPITE LA CONTRASEÑA:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, -1, -1));

        lblOlvidaste.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        lblOlvidaste.setForeground(new java.awt.Color(255, 153, 51));
        lblOlvidaste.setText("<html><u>Olvidaste tu contraseña?</u></html>");
        lblOlvidaste.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblOlvidaste.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblOlvidasteMouseClicked(evt);
            }
        });
        getContentPane().add(lblOlvidaste, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 520, -1, 40));
        getContentPane().add(txtContraRepRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 280, 25));
        getContentPane().add(txtContraRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 280, 25));
        getContentPane().add(txtCorreoRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 280, 25));
        getContentPane().add(txtUserRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 280, 25));

        jButton3.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon("D:\\CURSO BECA\\FUND DE PROGRAMACIÓN CON JAVA\\SESIONES\\SISTEMA-VENTAS\\FactuGo\\src\\main\\java\\com\\factug\\factugo\\ui\\imgs\\icon_register24.png")); // NOI18N
        jButton3.setText("Registrar");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, 120, 35));

        jButton2.setBackground(new java.awt.Color(255, 51, 51));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("X");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        lblRegistrar.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        lblRegistrar.setForeground(new java.awt.Color(255, 153, 51));
        lblRegistrar.setText("<html><u>Registrarse</u></html>");
        lblRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegistrarMouseClicked(evt);
            }
        });
        getContentPane().add(lblRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 520, -1, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon("D:\\CURSO BECA\\FUND DE PROGRAMACIÓN CON JAVA\\SESIONES\\SISTEMA-VENTAS\\FactuGo\\src\\main\\java\\com\\factug\\factugo\\ui\\imgs\\icon_user.png")); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 290, -1, -1));

        btnOcultar.setIcon(new javax.swing.ImageIcon("D:\\CURSO BECA\\FUND DE PROGRAMACIÓN CON JAVA\\SESIONES\\SISTEMA-VENTAS\\FactuGo\\src\\main\\java\\com\\factug\\factugo\\ui\\imgs\\icon_hidden.png")); // NOI18N
        btnOcultar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnOcultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOcultarMouseClicked(evt);
            }
        });
        getContentPane().add(btnOcultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 390, -1, -1));

        btnVer.setIcon(new javax.swing.ImageIcon("D:\\CURSO BECA\\FUND DE PROGRAMACIÓN CON JAVA\\SESIONES\\SISTEMA-VENTAS\\FactuGo\\src\\main\\java\\com\\factug\\factugo\\ui\\imgs\\icon_view.png")); // NOI18N
        btnVer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVerMouseClicked(evt);
            }
        });
        getContentPane().add(btnVer, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 390, -1, -1));

        lblITitulo1.setFont(new java.awt.Font("Rift Soft", 1, 44)); // NOI18N
        lblITitulo1.setText("REGISTRARSE");
        getContentPane().add(lblITitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, -1));

        lblITitulo.setFont(new java.awt.Font("Rift Soft", 1, 44)); // NOI18N
        lblITitulo.setText("INICIAR SESION");
        getContentPane().add(lblITitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 130, -1, -1));

        jLabel1.setFont(new java.awt.Font("Rift Soft", 1, 24)); // NOI18N
        jLabel1.setText("USUARIO:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, -1, -1));

        txtUsuario.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        getContentPane().add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 280, 280, 35));

        jLabel2.setFont(new java.awt.Font("Rift Soft", 1, 24)); // NOI18N
        jLabel2.setText("CONTRASEÑA:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 350, -1, -1));

        txtPass.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        getContentPane().add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 380, 280, 35));

        btnIngresar.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        btnIngresar.setIcon(new javax.swing.ImageIcon("D:\\CURSO BECA\\FUND DE PROGRAMACIÓN CON JAVA\\SESIONES\\SISTEMA-VENTAS\\FactuGo\\src\\main\\java\\com\\factug\\factugo\\ui\\imgs\\icon_login24.png")); // NOI18N
        btnIngresar.setText("Ingresar");
        btnIngresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 450, 180, 35));

        lblIngresar.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        lblIngresar.setForeground(new java.awt.Color(255, 153, 51));
        lblIngresar.setText("<html><u>Ingresar</u></html>");
        lblIngresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblIngresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIngresarMouseClicked(evt);
            }
        });
        getContentPane().add(lblIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, -1, 40));

        lblBg2.setIcon(new javax.swing.ImageIcon("D:\\CURSO BECA\\FUND DE PROGRAMACIÓN CON JAVA\\SESIONES\\SISTEMA-VENTAS\\FactuGo\\src\\main\\java\\com\\factug\\factugo\\ui\\imgs\\bg_logo_login.png")); // NOI18N
        getContentPane().add(lblBg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 400, 400));

        lblBg1.setIcon(new javax.swing.ImageIcon("D:\\CURSO BECA\\FUND DE PROGRAMACIÓN CON JAVA\\SESIONES\\SISTEMA-VENTAS\\FactuGo\\src\\main\\java\\com\\factug\\factugo\\ui\\imgs\\bg_logo_login.png")); // NOI18N
        getContentPane().add(lblBg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, 400, 400));

        switchButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                switchButton1MouseClicked(evt);
            }
        });
        getContentPane().add(switchButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 33, 18));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void switchButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_switchButton1MouseClicked
        // TODO add your handling code here:
        if(this.switchButton1.isSelected()){
            try {
                UIManager.setLookAndFeel(new FlatDarkLaf());
                SwingUtilities.updateComponentTreeUI(this);
            } catch (UnsupportedLookAndFeelException ex) {
                Logger.getLogger(FrmLogin.class.getName()).log(Level.SEVERE, null, ex);
            } 
        }else{
            try {
                UIManager.setLookAndFeel(new FlatLightLaf());
                SwingUtilities.updateComponentTreeUI(this);
            } catch (UnsupportedLookAndFeelException ex) {
                Logger.getLogger(FrmLogin.class.getName()).log(Level.SEVERE, null, ex);
            } 
        };
    }//GEN-LAST:event_switchButton1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed
    int posicionActual1 = 460;
    public void desplazamientoNegativo(){
        Timer mTimer = new Timer(5, (e) -> {
            posicionActual1 -= incremento;
            if (posicionActual1 >= 10 ) {
                lblBgImg.setLocation(posicionActual1, 10);
                //System.out.println(lblBgImg.getLocation());
            }
        });
        mTimer.setRepeats(true);
        mTimer.restart();
        posicionActual1 = 460;
    }
    private void lblIngresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIngresarMouseClicked
        // TODO add your handling code here:
        desplazamientoNegativo();
    }//GEN-LAST:event_lblIngresarMouseClicked
    
    int posicionActual = 10;
    int incremento = 10;
    public void desplazamiento(){
        Timer mTimer = new Timer(5, (e) -> {
            posicionActual += incremento;
            if (posicionActual <= 460 ) {
                lblBgImg.setLocation(posicionActual, 10);
                //System.out.println(lblBgImg.getLocation());
            }
        });
        mTimer.setRepeats(true);
        mTimer.restart();
        posicionActual=10;
    }
    private void lblRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegistrarMouseClicked
        // TODO add your handling code here:
        desplazamiento();
    }//GEN-LAST:event_lblRegistrarMouseClicked

    private void lblOlvidasteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOlvidasteMouseClicked
        // TODO add your handling code here:
        JOptionPane.showInputDialog("Ingrese su correo para enviar un correo de recuperacion de contraseña");
    }//GEN-LAST:event_lblOlvidasteMouseClicked
    
    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        // TODO add your handling code here:
        String usuario = txtUsuario.getText();
        String password = String.valueOf(txtPass.getPassword());
        
        UsuarioService servicio = new UsuarioServiceImpl();
        Usuario user = servicio.validar(usuario, password);
        
        if(usuario.equals("") || password.equals("")){
            JOptionPane.showMessageDialog(this, "Ingrese un usuario y contraseña valida");
        }else{
            if(user != null){
                Util.sesionUserNombre = user.getNombre();
                Util.sesionUser = user.getNombre() +" " +user.getApe_paterno() +" "+ user.getApe_materno();
                FrmMain frmMain = new FrmMain();
                frmMain.setVisible(true);
                //frmMain.setTitle("<html><b>BIENVENIDO: "+nombre.toUpperCase()+" "+ apePat.toUpperCase()+" " + apeMat.toUpperCase()+"</b></html>");
                this.dispose();
            }else{
                JOptionPane.showMessageDialog(this, "Datos incorrectos vuelve a intentarlo");
            }
            /*try {
                Connection cn = ConexionSQL.getConnection();
                PreparedStatement ps = cn.prepareStatement("select username, password, nombre , ape_paterno, ape_materno from usuarios where username= '" + usuario+ "' AND password= '"+password+"'; " );
                ResultSet rs = ps.executeQuery();
                if(rs.next()){
                    String nombre = rs.getString("nombre");
                    String apePat = rs.getString("ape_paterno");
                    String apeMat = rs.getString("ape_materno");
                    
                    FrmMain frmMain = new FrmMain();
                    
                    frmMain.setVisible(true);
                    frmMain.setTitle("<html><b>BIENVENIDO: "+nombre.toUpperCase()+" "+ apePat.toUpperCase()+" " + apeMat.toUpperCase()+"</b></html>");
                    this.dispose();
                    
                    //System.out.println(rs.getString("nombre"));
                    
                }else{
                    JOptionPane.showMessageDialog(this, "Datos incorrectos vuelve a intentarlo");
                }
            } catch (SQLException ex) {
                System.out.println("error de conexion " +ex);
            }  
        //return null;*/  
        }
        
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void btnVerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVerMouseClicked
        // TODO add your handling code here
        btnVer.setVisible(false);
        btnOcultar.setVisible(true);
        txtPass.setEchoChar((char)0);
    }//GEN-LAST:event_btnVerMouseClicked

    private void btnOcultarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOcultarMouseClicked
        // TODO add your handling code here:
        btnVer.setVisible(true);
        btnOcultar.setVisible(false);
        txtPass.setEchoChar('\u2022');
    }//GEN-LAST:event_btnOcultarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JLabel btnOcultar;
    private javax.swing.JLabel btnVer;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblBg1;
    private javax.swing.JLabel lblBg2;
    private javax.swing.JLabel lblBgImg;
    private javax.swing.JLabel lblITitulo;
    private javax.swing.JLabel lblITitulo1;
    private javax.swing.JLabel lblIngresar;
    private javax.swing.JLabel lblOlvidaste;
    private javax.swing.JLabel lblRegistrar;
    private com.factug.factugo.ui.SwitchButton switchButton1;
    private javax.swing.JPasswordField txtContraRegister;
    private javax.swing.JPasswordField txtContraRepRegister;
    private javax.swing.JTextField txtCorreoRegister;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUserRegister;
    public static javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

}
