
package com.factug.factugo.ui;

import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Color;
import java.awt.event.ActionListener;
import javax.swing.Timer;
import javax.swing.UIManager;

/**
 *
 * @author Jhordie
 */
public class Splashscreen extends javax.swing.JFrame {
    
    private Color mTransparent;
    
    /** Creates new form Splashscreen */
    public Splashscreen() {
        mTransparent = new Color(0,0,0,0);
        FlatLightLaf.setup();
        UIManager.put( "ProgressBar.arc", 999 );
        
        
        setUndecorated(true);
        initComponents();
        setLocationRelativeTo(null);
        setBackground(mTransparent);
      
        Carga();
    }
    public void Carga(){
        Timer mTimer = new Timer(45, (e) -> {
           pbCarga.setValue(pbCarga.getValue() + 1);
           //pbCarga.setBackground(mTransparent);
           //pbCarga.setStringPainted(true);
           lblCarga.setText(pbCarga.getValue() +"%");
           lblCarga1.setText(pbCarga.getValue() +"%");
        });
        mTimer.start();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCarga = new javax.swing.JLabel();
        lblCarga1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pbCarga = new javax.swing.JProgressBar();
        imgsplash = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCarga.setFont(new java.awt.Font("Rift Soft", 1, 28)); // NOI18N
        lblCarga.setForeground(new java.awt.Color(255, 255, 255));
        lblCarga.setText("0%");
        getContentPane().add(lblCarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 570, -1, -1));

        lblCarga1.setFont(new java.awt.Font("Rift Soft", 1, 29)); // NOI18N
        lblCarga1.setForeground(new java.awt.Color(153, 153, 153));
        lblCarga1.setText("0%");
        getContentPane().add(lblCarga1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 570, -1, -1));

        jLabel2.setFont(new java.awt.Font("Rift Soft", 1, 28)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cargando...");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 570, -1, -1));

        jLabel3.setFont(new java.awt.Font("Rift Soft", 1, 29)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Cargando...");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 570, -1, -1));

        pbCarga.setFont(new java.awt.Font("Open Sans", 1, 24)); // NOI18N
        pbCarga.setForeground(new java.awt.Color(255, 153, 51));
        pbCarga.setBorder(null);
        getContentPane().add(pbCarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 610, 320, 12));

        imgsplash.setIcon(new javax.swing.ImageIcon("D:\\CURSO BECA\\FUND DE PROGRAMACIÓN CON JAVA\\SESIONES\\SISTEMA-VENTAS\\FactuGo\\src\\main\\java\\com\\factug\\factugo\\ui\\imgs\\Splash.png")); // NOI18N
        getContentPane().add(imgsplash, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 740));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel( new FlatLightLaf() );
            UIManager.put( "Component.arc", 999 );
            UIManager.put( "ProgressBar.arc", 999 );
        } catch( Exception ex ) {
            System.err.println( "Failed to initialize LaF" );
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Splashscreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imgsplash;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblCarga;
    private javax.swing.JLabel lblCarga1;
    private javax.swing.JProgressBar pbCarga;
    // End of variables declaration//GEN-END:variables

}
